Update COC for improved diversity and inclusion
pygreece/community pull request #13
Opened 2024-12-04 18:06 UTC by vadal

2024-12-04 18:15 UTC, thepetk commented on docs/el/code-of-conduct.md
> +υποστήριξη, παρακαλούμε ενημερώστε μας και θα προσπαθήσουμε να σας υποστηρίξουμε
Βάζω και έναν τρόπο επικοινωνίας
```suggestion
υποστήριξη, παρακαλούμε ενημερώστε μας (email στο organizers@pygreece.org) και θα προσπαθήσουμε να σας υποστηρίξουμε
```

2024-12-04 18:15 UTC, thepetk commented on docs/el/code-of-conduct.md
> +[coc@pygreece.org](mailto:coc@pygreece.org) για να υποβάλουν ένσταση σχετικά με την
Στην ουσία αποβάλλονται με απόφαση του διοικητικού όχι του CoC committee. Νομίζω πως η συγκεκριμένη πρόταση ταιριάζει περισσότερο στα principles. wdyt?
```suggestion
[organizers@pygreece.org](mailto:organizers@pygreece.org) για να υποβάλουν ένσταση σχετικά με την
```

2024-12-04 18:15 UTC, thepetk commented on docs/el/code-of-conduct.md
> +Για οποιαδήποτε ανησυχία ή αναφορά για ανάρμοστη συμπεριφορά, μπορείτε να επικοινωνήσετε
εδώ θα μπορούσαμε να αναφέρουμε και την ομάδα που διαχειρίζεται τα αιτήματα ώστε να είναι ξεκάθαρο ποιο άτομο θα διαβάσει το αίτημα.

2024-12-06 11:50 UTC, vadal commented on docs/el/code-of-conduct.md
> +[coc@pygreece.org](mailto:coc@pygreece.org) για να υποβάλουν ένσταση σχετικά με την
Μου φαίνεται σχετικό με τις Συνέπειες. Αλλά πως το εννοείς; Να το μεταφέρουμε σε άλλο σημείο στο document;

2024-12-06 18:07 UTC, thepetk commented on docs/el/code-of-conduct.md
> +[coc@pygreece.org](mailto:coc@pygreece.org) για να υποβάλουν ένσταση σχετικά με την
Θα μπορούσαμε να το αναφέρουμε και δω. Μια χαρα ειναι. Το μόνο που πιστεύω οτι θα πρεπει σίγουρα να αλλάξει ειναι πως το CoC Commitee δεν παίρνει αποφάσεις ή ενστάσεις απλώς χειρίζεται καταστάσεις και γνωμοδοτεί στους διοργανωτές. Άρα η οποιαδήποτε ένσταση αφορά την απόφαση των organizers.

2024-12-13 16:37 UTC, vadal commented on docs/el/code-of-conduct.md
> +με την ομάδα διαχείρισης στο [coc@pygreece.org](mailto:coc@pygreece.org). Όλες οι αναφορές
```suggestion
με την αρμόδια διμελή επιτροπή στο [coc@pygreece.org](mailto:coc@pygreece.org), που έχει οριστεί για να διαχειρίζεται αυτές τις περιπτώσεις με απόλυτη διακριτικότητα και εμπιστευτικότητα.
```

2024-12-13 16:38 UTC, vadal commented on docs/el/code-of-conduct.md
> +θα διαχειρίζονται με εμπιστευτικότητα και με προτεραιότητα στη διασφάλιση της ευημερίας
```suggestion
Τα μέλη της επιτροπής είναι:
```

2024-12-13 16:40 UTC, vadal commented on docs/el/code-of-conduct.md
> +των μελών μας.
```suggestion

- ο Λύσανδρος Νικολάου, και
- η Βασιλική Δαλακιάρη

```

2024-12-13 22:10 UTC, thepetk commented on docs/el/code-of-conduct.md
> +με την ομάδα διαχείρισης στο [coc@pygreece.org](mailto:coc@pygreece.org). Όλες οι αναφορές
το επιτροπή μου κάνει λίγο επίσημο ε; Μήπω να το κρατούσαμε ομάδα;

2024-12-13 22:44 UTC, thepetk commented
@vadal @lysnikolaou δημιούργησα το coc@pygreece.org και σας εβαλα ως owners. Μια σκέψη είναι πως μελλοντικά το συγκεκριμένο γκρουπ θα πρεπει να ειναι ανεξαρτητο από το google workspace μας ή τουλάχιστον τα ατομα που ειναι admins να μην έχουν access (πχ αυτή την στιγμή μπορω να βαλω τον εαυτο μου στο γκρουπ και να δω τα μνμτα). Αλλα το κοιταμε στην πορεια.

Έχω στειλει ενα τεστ report μπορειται να το τσεκαρετε;

2024-12-14 09:42 UTC, vadal commented
Το έλαβα!

2024-12-14 16:02 UTC, thepetk commented
@vadal νομιζω το αγγλικο κείμενο θέλει ένα update για να είναι ίδιο με το ελληνικό.

2024-12-14 17:04 UTC, vadal commented
Done!

2024-12-14 17:51 UTC, thepetk commented
@vadal προσπάθησα να κάνω gender neutral την ελληνική έκδοση του coc. Αν θες ρίξε και συ μια ματιά.

Οι αλλαγές σου lgtm, ωστόσο ας κάνουμε και μια ψηφοφορία πριν τις κανουμε merge.

2024-12-14 18:03 UTC, thepetk commented
> @vadal προσπάθησα να κάνω gender neutral την ελληνική έκδοση του coc. Αν θες ρίξε και συ μια ματιά ([a6c17a4](https://github.com/pygreece/community/pull/13/commits/a6c17a4401239dbc69fab9a0688d7b4537352d78)).
> 
> Οι αλλαγές σου lgtm, ωστόσο ας κάνουμε και μια ψηφοφορία πριν τις κανουμε merge.

Έκανα το ίδιο και στα υπόλοιπα docs

2024-12-15 10:40 UTC, vadal commented
Εξαιρετικά!

2024-12-16 07:55 UTC, skpanagiotis requested changes
Πολύ καλή δουλειά, φαίνεται πόσο χρόνο έχετε ξοδέψει για να είναι αψεγάδιαστο. Πρόσθεσα μόνο δύο μικρά suggestions.

2024-12-16 07:55 UTC, skpanagiotis commented on docs/el/code-of-conduct.md
> +συμμετέχουν να έχουν μια ευχάριστη και ικανοποιητική εμπειρία. Κατα συνέπεια, όλα τα άτομα
```suggestion
συμμετέχουν να έχουν μια ευχάριστη και ικανοποιητική εμπειρία. Κατά συνέπεια, όλα τα άτομα
```

2024-12-16 07:55 UTC, skpanagiotis commented on docs/el/code-of-conduct.md
> +προσανατολισμό, την αναπηρία, τη σωματική εμφάνιση, το μέγεθος σώματος, την εθνικότητα, τη
```suggestion
προσανατολισμό, την αναπηρία, τη σωματική εμφάνιση, το σωματότυπο, την εθνικότητα, τη
```

2024-12-16 16:39 UTC, lysnikolaou reviewed
Τέλεια. Νομίζω είναι πολύ καλό improvement! Thanks @vadal και @thepetk!

Άφησα μερικά comments. Επίσης συμφωνώ και τα 2 comments που έκανε από πάνω ο @skpanagiotis!

2024-12-16 16:39 UTC, lysnikolaou commented on docs/el/code-of-conduct.md
>  συνεργασία όλων των κοινοτήτων προγραμματιστών Python στην Ελλάδα.
```suggestion
Το PyGreece είναι μια κοινότητα ατόμων που ασχολούνται με την Python, που έχει ώς στόχο την δικτύωση και
την συνεργασία ανάμεσα σε όλες τις κοινότητες Python στην Ελλάδα.
```

2024-12-16 16:39 UTC, lysnikolaou commented on docs/el/code-of-conduct.md
>  όλους.**
```suggestion
όλα τα μέλη μας.**
```

2024-12-16 16:39 UTC, lysnikolaou commented on docs/el/principles.md
> +νομική ισχύ.
Αυτό εδώ μάλλον καλύτερα να γίνει reverted. Για να γίνει σωστά rendered το info box, χρειαζεται να ειναι indented.

2024-12-16 16:39 UTC, lysnikolaou commented on docs/en/code-of-conduct.md
> +inform us, and we will do our best to accommodate.
```suggestion
inform us at [organizers@pygreece.org](mailto:organizers@pygreece.org), and we will do our best to accommodate.
```

2024-12-16 17:23 UTC, vadal commented on docs/el/principles.md
> +Το διοικητικό συμβούλιο της PyGreece AMKE δουλεύει αυτήν την περίοδο πάνω στην νομική
```suggestion
    Το διοικητικό συμβούλιο της PyGreece AMKE δουλεύει αυτήν την περίοδο πάνω στην νομική
```

2024-12-16 17:24 UTC, vadal commented on docs/el/principles.md
> +μορφή της κοινότητας PyGreece. Επομένως, αν και θεωρούνται σημαντικό κομμάτι της
```suggestion
    μορφή της κοινότητας PyGreece. Επομένως, αν και θεωρούνται σημαντικό κομμάτι της
```

2024-12-16 17:24 UTC, vadal commented on docs/el/principles.md
> +λειτουργίας της κοινότητας, οι κανόνες που αναφέρονται παρακάτω δεν έχουν ακόμα κάποια
```suggestion
    λειτουργίας της κοινότητας, οι κανόνες που αναφέρονται παρακάτω δεν έχουν ακόμα κάποια
```

2024-12-16 17:24 UTC, vadal commented on docs/el/principles.md
> +νομική ισχύ.
```suggestion
    νομική ισχύ.
```

2024-12-16 17:38 UTC, vadal commented on docs/el/principles.md
> +> **ΣΗΜΑΝΤΙΚΟ:** Το διοικητικό συμβούλιο της PyGreece AMKE δουλεύει αυτήν την περίοδο πάνω
@lysnikolaou δες αυτό. Το προηγούμενο φαίνεται να μην γίνεται render σωστά (ούτε στο master).

2024-12-16 17:56 UTC, lysnikolaou commented on docs/el/principles.md
> +> **ΣΗΜΑΝΤΙΚΟ:** Το διοικητικό συμβούλιο της PyGreece AMKE δουλεύει αυτήν την περίοδο πάνω
Οποτε νομιζω οτι πρεπει μαλλον ακομη να κανουμε revert.

2024-12-16 17:59 UTC, vadal commented on docs/el/principles.md
> +> **ΣΗΜΑΝΤΙΚΟ:** Το διοικητικό συμβούλιο της PyGreece AMKE δουλεύει αυτήν την περίοδο πάνω
Ok, πάντως αυτό βλέπω στο main.
<img width="1394" alt="Screenshot 2024-12-16 at 7 58 30 PM" src="https://github.com/user-attachments/assets/3b7c7e05-5c3e-46f6-97d2-a6254469031f" />

2024-12-16 18:01 UTC, lysnikolaou commented on docs/el/principles.md
> +> **ΣΗΜΑΝΤΙΚΟ:** Το διοικητικό συμβούλιο της PyGreece AMKE δουλεύει αυτήν την περίοδο πάνω
Στο website στο pygreece.org η στο Github?

2024-12-16 18:05 UTC, vadal commented on docs/el/principles.md
> +> **ΣΗΜΑΝΤΙΚΟ:** Το διοικητικό συμβούλιο της PyGreece AMKE δουλεύει αυτήν την περίοδο πάνω
```suggestion
!!! info "ΣΗΜΑΝΤΙΚΟ"
    Το διοικητικό συμβούλιο της PyGreece AMKE δουλεύει αυτήν την περίοδο πάνω
```

2024-12-16 18:05 UTC, vadal commented on docs/el/principles.md
> +> στην νομική μορφή της κοινότητας PyGreece. Επομένως, αν και θεωρούνται σημαντικό κομμάτι
```suggestion
    στην νομική μορφή της κοινότητας PyGreece. Επομένως, αν και θεωρούνται σημαντικό κομμάτι
```

2024-12-16 18:05 UTC, vadal commented on docs/el/principles.md
> +> της λειτουργίας της κοινότητας, οι κανόνες που αναφέρονται παρακάτω δεν έχουν ακόμα
```suggestion
    της λειτουργίας της κοινότητας, οι κανόνες που αναφέρονται παρακάτω δεν έχουν ακόμα
```

2024-12-16 18:05 UTC, vadal commented on docs/el/principles.md
> +> κάποια νομική ισχύ.
```suggestion
    κάποια νομική ισχύ.
```

2024-12-16 18:06 UTC, vadal commented on docs/el/principles.md
> +> **ΣΗΜΑΝΤΙΚΟ:** Το διοικητικό συμβούλιο της PyGreece AMKE δουλεύει αυτήν την περίοδο πάνω
Στο github. Το άλλαξα, πρέπει να το βλέπεις οκ τώρα;

2024-12-17 08:50 UTC, skpanagiotis approved these changes

2024-12-22 18:21 UTC, thepetk commented
Approved & voted <3

2024-12-22 18:22 UTC, merged